name:                EarleyM
version:             0.1.0.0
synopsis:            Monadic Earley Parsing
description:         Monadic combinators for Earley Parsing
homepage:            https://github.com/Nick-Chapman/EarleyM
license:             BSD3
author:              Nick Chapman
maintainer:          nic@amadido.co.uk
category:            Parsing
github:              Nick-Chapman/EarleyM

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- containers >= 0.5 && < 0.7
- HMap >= 1.3 && < 1.4

library:
  source-dirs: src
  ghc-options:        -Wall

tests:
  EarleyM-test:
    main:                Main.hs
    source-dirs:         [examples, test]
    other-modules:
    - UnitTest
    - Testing
    - Example.Catalan
    - Example.PrepositionalAttachmentAmbiguity
    - Example.FunctionalLanguage
    - Example.DictionaryLexing
    - Example.Arith
    ghc-options:        -Wall
    dependencies:       EarleyM
